name: Build & publish Astrojs site to Github Pages

on:
    # Run on pushes from other repo
    repository_dispatch:
    # Manually run from the Actions tab
    workflow_dispatch:

# Environment variables
env:
    commit_update_message: Publishing update

# Allow only one concurrent deployment
concurrency:
    group: pages
    cancel-in-progress: true

jobs:
    # Building & publishing website
    build:
        permissions:
            contents: read
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository with git
              uses: actions/checkout@v4
            
            - name: Generating env. file
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  echo REPOSITERY_PAGE="$(gh api 'repos/${{ github.repository }}/pages' --jq '.html_url')" >> .env
                  echo REPOSITERY_URL="${{ github.repository }}" >> .env
                  echo REPOSITERY_OWNER="${{ github.repository_owner }}" >> .env
                  echo SERVER_URL="${{ github.server_url }}" >> .env

            - name: Build with docker
              run: |
                docker build --target build-static -t build .
                docker cp build:/web/dist /tmp/build
            
            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: /tmp/build

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4