name: Update submodules

on:
  # Run on pushes targeting main branches
  push:
    tags:
      - "*"
  # Run on pushes from other repo
  repository_dispatch:
  # Manually run from the Actions tab
  workflow_dispatch:

env:
  commit_msg: Submodule update

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Config git
        run: |
          git config --global user.name '${{ github.repository_owner }}'
          git config --global user.email '${{ github.repository_owner }}@users.noreply.github.com'
      - name: Update submodule
        run: |
          git submodule foreach --recursive \
          "git add . && git commit -m '${{ env.commit_msg }}' && git push"
          exit 0
      - name: Update itself
        run: 
          git add .
          git commit -m '${{ env.commit_msg }}'
          git push